# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme: "minimal-mistakes-jekyll"
theme: "minima"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en_US"
title: Raúl Fernández Fernández
title_separator: " | "
subtitle: "A blog about programming, life, and other things"
name: "Raúl Fernández Fernández"
description: >- # this means to ignore newlines until "baseurl:"
  Raúl Fernández Fernández personal website.
url: "https://raulfernandez.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
domain:
  - raulfernandez.dev
repository: "rfdez/rfdez.github.io"
teaser: "assets/images/android-chrome-512x512.png"
logo: "assets/images/android-chrome-512x512.png"
masthead_title: "Raúl Fernández Fernández"

# Breadcrumbs
words_per_minute: 200

# Analytics
analytics:
  google:
    tracking_id: G-221JLRHCY7
    anonymize_ip: false

# Site Author
author:
  name: "Raúl Fernández Fernández"
  avatar: "assets/images/android-chrome-512x512.png"
  bio: "I am an **amazing** person."
  location: "Madrid, Spain"
  email: info@raulfernandez.dev
  links:
    - label: "GitHub"
      url: "https://github.com/rfdez"
      icon: "fab fa-fw fa-github"

# Site Footer
footer:
  links:
    - label: "GitHub"
      url: ""
      icon: "fab fa-fw fa-github"

# Reading Files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .editorconfig
  - Makefile
keep_files:
  - .git
  - .svn
encoding: "UTF-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
